schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PublicEnvironmentInput"
  types:
    PublicEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        vpc_cidr:
          type: string
          description: "This CIDR range for your VPC"
          default: 10.0.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        public_subnet_one_cidr:
          type: string
          description: "The CIDR range for public subnet one"
          default: 10.0.0.0/18
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        public_subnet_two_cidr:
          type: string
          description: "The CIDR range for public subnet two"
          default: 10.0.64.0/18
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        private_subnet_one_cidr:
          type: string
          description: "The CIDR range for private subnet one"
          default: 10.0.128.0/18
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        private_subnet_two_cidr:
          type: string
          description: "The CIDR range for private subnet two"
          default: 10.0.192.0/18
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        aws_region:
          title: AWS Region
          type: string
          description: AWS Region where resources will reside
          default: us-east-1
        tf_state_bucket:
          title: Terraform state storage S3 bucket
          type: string
          description: S3 Bucket to store Terraform state
          default: s3-bucket-name-here
        tf_state_bucket_region:
          title: State bucket AWS Region
          type: string
          description: AWS Region where state bucket resides
          default: us-east-1