schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "VpcEnvironmentInput"

  types:
    VpcEnvironmentInput:
      type: object
      description: "Input properties for a vpc environment."
      properties:
        vpc_name:
          type: string
          description: "Name for vpc"
      required:
        - vpc_name
