schema:
  format:
    openapi: "3.0.0"
  service_input_type: "ScheduledECSEC2TaskInput"
  pipeline_input_type: "PipelineInputs"

  types:
    ScheduledECSEC2TaskInput:
      type: object
      description: "Input properties for Scheduled ECSEC2 Task"
      properties:
        desired_count:
          type: number
          description: "The default number of ECSEC2 tasks you want running"
          default: 1
          minimum: 1
        task_size:
          type: string
          description: "The size of the task you want to run"
          enum: ["x-small", "small", "medium", "large", "x-large"]
          default: "x-small"
        image:
          type: string
          description: "The name/url of the container image"
          default: "public.ecr.aws/z9d2n7e1/nginx:1.21.0"
          minLength: 1
          maxLength: 200
        schedule_expression:
          type: string
          description: "The schedule or rate (frequency) for CloudWatch Events"
          default: "rate(5 minutes)"
          minLength: 1
          maxLength: 200

    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        service_dir:
          type: string
          description: "Source directory for the service"
          default: "ecs-ping-sns"
          minLength: 1
          maxLength: 100
        dockerfile:
          type: string
          description: "The location of the Dockerfile to build"
          default: "Dockerfile"
          minLength: 1
          maxLength: 100
        unit_test_command:
          type: string
          description: "The command to run to unit test the application code"
          default: "echo 'add your unit test command here'"
          minLength: 1
          maxLength: 200
        environment_account_ids:
          type: string
          pattern: '^$|^\d{12}(,\d{12})*$'
          description: "The environment account ids for service instances using cross account environment, separated by ,"
          default: ""
          maxLength: 200
